name: Automated E2E Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Run Cypress tests with Electron
        uses: cypress-io/github-action@v4.1.0
        with:
          browser: electron
